repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(gridcp|tests)/.*\.py$
        exclude: ^gridcp/old_api/
      - id: ruff-format
        files: ^(gridcp|tests)/.*\.py$
        exclude: ^gridcp/old_api/
